# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=14)),
                ('deuda', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('dias_mora', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.Cliente')),
            ],
        ),
    ]
